### ISSUE TITLE
搜索页面无法搜到灰色歌曲

### ISSUE THREAD

**Issue by Noah19981115** [Sherlockouo/music#10]
比如搜陈绮贞的秋天蒙太奇，是搜不到的，因为这首歌在的专辑时间的歌在网易云是灰的，但如果进入点进歌手页面进入这张专辑才可以听到

**Comment by Sherlockouo** [comment]
这个可能暂时还没办法，因为搜索接口是网易云的，网易云自己接口把他屏蔽了应该是。
