### ISSUE TITLE
桌面歌词

### ISSUE THREAD

**Issue by Sherlockouo** [Sherlockouo/music#13]
阿里嘎多

**Comment by Sherlockouo** [comment]
没有美工，我就随意了哈哈哈。
<img width="1180" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/3c97e0b0-5233-48a3-aa2b-521e01fc8537">

**Comment by yuzh0816** [comment]
Windows上有显示Bug：闪动歌词【录屏时没有滚动鼠标/键盘】。

https://github.com/Sherlockouo/music/assets/46953451/7fcee8f9-ae55-4069-a6aa-5d81df607009

**Comment by Sherlockouo** [comment]
> Windows上有显示Bug：闪动歌词【录屏时没有滚动鼠标/键盘】。
> 
>  Toronto.-.R3PLAYX.2023-11-11.21-41-55.mp4

好像是有这个问题，开关一下就好了。暂时还没修
