### ISSUE TITLE
[BUG] 菜单未正确本地化

### ISSUE THREAD

**Issue by cnrenil** [Sherlockouo/music#138]
## 描述
菜单在Linux/MacOS上未正确本地化，因为Electron没有提供官方的Menu Role翻译，比如View就没有翻译，似乎需要全部自己实现翻译。。如果可以的话希望修复一下，主要是风格不是很统一，中英文混合了。
## 截图
![屏幕截图_20240706_231946](https://github.com/Sherlockouo/music/assets/110750103/687ab0f8-2042-4a22-b8f5-2bb1acd0ba16)
## 相关ISSUE
[Electron #26231](https://github.com/electron/electron/issues/26231)

**Comment by jinzhongjia** [comment]
这些 bar 是 electron 默认的，music 并没有设置这个

**Comment by cnrenil** [comment]
> 这些 bar 是 electron 默认的，music 并没有设置这个

了解的，许多electron程序都有这个问题，需要自己实现翻译。我个人是有点点强迫症的，全部调成英文也是可以的🙃
