### ISSUE TITLE
快捷键

### ISSUE THREAD

**Issue by Sherlockouo** [Sherlockouo/music#18]
快捷键支持
<img width="881" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/25cceb28-f046-427f-9575-da8da9ba15f8">

**Comment by IvanLi-CN** [comment]
目前实现的样子：

<img width="1671" alt="image" src="https://github.com/Sherlockouo/music/assets/30215105/80eb1657-d611-41b7-8b68-a8d22f59b46d">

**Comment by IvanLi-CN** [comment]
增加了一组全局菜单，用于绑定应用内快捷键

<img width="367" alt="image" src="https://github.com/Sherlockouo/music/assets/30215105/c5282a31-855b-487f-8e89-fd2c3f93e040">

**Comment by IvanLi-CN** [comment]
我遇到一个问题：目前键盘是能操作 UI 的，和快捷键可能会冲突。尤其是我比较喜欢直接使用空格键暂停和播放音乐，但是焦点在按钮上时，按空格键会触发按钮。像这种触发按钮的操作是不是应该禁用掉？代价是没办法使用键盘操作 UI。

**Comment by IvanLi-CN** [comment]
应用内的快捷键是否允许没有修饰键？

没有修饰键，可以不用按组合键，但是需要在输入框临时屏蔽快捷键；
需要修饰键，按着比较麻烦，但是不太可能冲突。

我是比较倾向不用修饰键，尤其是播放/暂停。

**Comment by IvanLi-CN** [comment]
应用内的快捷键是否允许没有修饰键？

没有修饰键，可以不用按组合键，但是需要在输入框临时屏蔽快捷键；
需要修饰键，按着比较麻烦，但是不太可能冲突。

我是比较倾向不用修饰键，尤其是播放/暂停。

**Comment by IvanLi-CN** [comment]
应用内的快捷键是否允许没有修饰键？

没有修饰键，可以不用按组合键，但是需要在输入框临时屏蔽快捷键；
需要修饰键，按着比较麻烦，但是不太可能冲突。

我是比较倾向不用修饰键，尤其是播放/暂停。

**Comment by Sherlockouo** [comment]
感觉可以不用修饰键，输入的时候短暂屏蔽下就好了。


> 我遇到一个问题：目前键盘是能操作 UI 的，和快捷键可能会冲突。尤其是我比较喜欢直接使用空格键暂停和播放音乐，但是焦点在按钮上时，按空格键会触发按钮。像这种触发按钮的操作是不是应该禁用掉？代价是没办法使用键盘操作 UI。

这个没看明白，键盘和快捷键冲突是指 和系统的快捷键冲突吗？

**Comment by IvanLi-CN** [comment]
> 这个没看明白，键盘和快捷键冲突是指 和系统的快捷键冲突吗？



[视频](https://s3.ivanli.cc/ivan-public/uPic/2023/kclHbQ.mp4)

视频最开始，焦点在列表的时候，我连续按了两下空格键，按空格键会翻页；然后点击了一次上面的按钮，之后按空格键会触发点击事件，音乐开始播放，最后生效的是按钮的事件。然后我又绑定了空格键作为播放/暂停，所以会同时触发。我觉得浏览器默认的空格键行为应该屏蔽掉。

**Comment by Sherlockouo** [comment]
这个视频看不鸟
<img width="516" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/6b69ff5e-9663-4c03-bb54-29453615edcd">

**Comment by Sherlockouo** [comment]
可以屏蔽浏览器默认绑定的快捷键，不然就是一些隐藏逻辑，用户用着会很麻烦。

**Comment by IvanLi-CN** [comment]
如果有问题的话再打开。
