### ISSUE TITLE
M1 页面左上角按钮显示问题

### ISSUE THREAD

**Issue by YvGuo-YY** [Sherlockouo/music#27]
<img width="423" alt="image" src="https://github.com/Sherlockouo/music/assets/54350593/0f343e9d-4b63-4160-a7f1-2188d928423b">
<img width="505" alt="image" src="https://github.com/Sherlockouo/music/assets/54350593/a0e1e3ba-3780-4c9a-a133-ebe7d0a732a3">

**Comment by YvGuo-YY** [comment]
正常状态：
<img width="370" alt="image" src="https://github.com/Sherlockouo/music/assets/54350593/d7522605-2321-4c2d-836d-6ff9aea6f129">
鼠标滑动到按钮上层：
<img width="285" alt="image" src="https://github.com/Sherlockouo/music/assets/54350593/f14dd67e-9656-435c-ad3f-aef0f95b7682">

**Comment by Sherlockouo** [comment]
是这样的，新版会修复这个问题

**Comment by yuzh0816** [comment]
Already fixed.
