### ISSUE TITLE
🎉 歌曲音频特效

### ISSUE THREAD

**Issue by Sherlockouo** [Sherlockouo/music#31]

**Comment by Sherlockouo** [comment]
<img width="1526" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/58960cd1-2b00-4d33-bd14-4f78789ae67f">

**Comment by Sherlockouo** [comment]
这个canvas画的东西在最上层有点恼火 emmm。

**Comment by kksxsyj** [comment]
我个人觉得1.x版本的那个歌词特效页面就挺好看的，这个设计上反而有种审美倒退的感觉，或者参考一下用插件修改后的spotify歌词页面也可以，当然仅仅是我非常个人的看法。
![截屏2023-10-20 00 20 48](https://github.com/Sherlockouo/music/assets/74647878/0707f4f6-b5fb-477d-a764-716a1e4b8c24)

**Comment by yuzh0816** [comment]
> 我个人觉得1.x版本的那个歌词特效页面就挺好看的，这个设计上反而有种审美倒退的感觉，或者参考一下用插件修改后的spotify歌词页面也可以，当然仅仅是我非常个人的看法。 ![截屏2023-10-20 00 20 48](https://user-images.githubusercontent.com/74647878/276683684-0707f4f6-b5fb-477d-a764-716a1e4b8c24.png)

同感，其实感觉没有必要做成这样的设计，不是很好看。

**Comment by Sherlockouo** [comment]
所以他是一个可选项，不是强制要求开启的。

**Comment by Sherlockouo** [comment]
![image](https://github.com/Sherlockouo/music/assets/34598208/cf003e7f-23a9-4b2a-b89c-773fafa60145)

**Comment by Sherlockouo** [comment]
着实不雅，被我干掉了
