### ISSUE TITLE
功能请求：歌单页面增加名称显示

### ISSUE THREAD

**Issue by IvanLi-CN** [Sherlockouo/music#32]
<img width="1674" alt="image" src="https://github.com/Sherlockouo/music/assets/30215105/2d43bc43-2b0e-41d9-a594-875b87e158fc">

上图这个界面。看图片不知道这个歌单是什么主题的，我现在每次点进去看一眼又出来，有点要命。

是否可以增加歌单名称显示？一直显示或者指针悬浮时显示之类的。

**Comment by Sherlockouo** [comment]
可以考虑在cover下面加一个歌单名称
