### ISSUE TITLE
媒体控制里不展示cover

### ISSUE THREAD

**Issue by Sherlockouo** [Sherlockouo/music#39]
<img width="354" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/a27798f4-75bd-421b-9c6f-955af16faaa2">

**Comment by lu0se** [comment]
electron/electron#40469,linux上不展示cover应该是electron的bug,相同代码在Chromium上cover正常显示

**Comment by Sherlockouo** [comment]
怪哉
