### ISSUE TITLE
The currently specified pnpm version does not support version 6 lockfile

### ISSUE THREAD

**Issue by IvanLi-CN** [Sherlockouo/music#46]
[pnpm v8.0.0-rc.0](https://github.com/pnpm/pnpm/releases/tag/v8.0.0-rc.0#:~:text=Lockfile%20modifications%3A)

> This lockfile is supported in pnpm v7 as an opt-in, so if someone in your team is still using pnpm v7, you may set use-lockfile-v6=true in an .npmrc file in the root of the project and even pnpm v7 will read and write the lockfile in the new format.

从上面的信息可知项目指定的 pnpm@7.20.0 默认不支持 v6 版本的 lockfile，这会导致每次安装依赖时忽略 lockfile。

目前我没验证成功  pnpm@7.20.0 能通过 use-lockfile-v6=true 启用相关支持， pnpm@7.33.6 可以；如果使用 pnpm@8.10.2 ，默认配置就能够正确安装依赖。

我不确定是不是我的环境或者操作有问题，每次 rebase 代码时都会启动不了项目，后面看下 lockfile 被覆盖了，一步步排查到这了。

如果问题存在的话，我建议将 node.js 版本要求提升到 20，pnpm 版本锁定在 8.10.2。

**Comment by Sherlockouo** [comment]
那把这个lockfile忽略了 能解决？

**Comment by IvanLi-CN** [comment]
忽略 lockfile 的话我这装完依赖后运行，会报告很多类型错误，运行不了。

我之前更新代码后，都跑不了，最后重新 clone 项目才行…… 而且我怀疑是我操作有问题才导致重新 clone 项目能用。

我觉得现在项目应该是要用 pnpm v8 版本才能正常使用 corepack pnpm install 来安装依赖。
