### ISSUE TITLE
M1 Pro歌词显示问题

### ISSUE THREAD

**Issue by YvGuo-YY** [Sherlockouo/music#47]
{"message":"Route GET:/desktoplyrics not found","error":"Not Found","statusCode":404}
歌词显示有问题
<img width="1214" alt="image" src="https://github.com/Sherlockouo/music/assets/54350593/d0de6fff-5c8f-409d-838c-35aaa89e347f">

**Comment by Sherlockouo** [comment]
已修复，还未发布
