### ISSUE TITLE
Appimage没有启动

### ISSUE THREAD

**Issue by clean-master** [Sherlockouo/music#52]
```bash
./R3PLAYX-2.7.0-Pre-linux.AppImage                                                                                                                                                                                               
```
``` 
22:32:10 info › 

   _  __   __     _     ____                    __  ___                    _        
  | |/ /  / /_   (_)   / __/   __  __          /  |/  /  __  __   _____   (_)  _____
  |   /  / __/  / /   / /_    / / / /         / /|_/ /  / / / /  / ___/  / /  / ___/ 
 /   |  / /_   / /   / __/   / /_/ /         / /  / /  / /_/ /  (__  )  / /  / /__  
/_/|_|  \__/  /_/   /_/      \__, /         /_/  /_/   \__,_/  /____/  /_/   \___/  
                            /____/

22:32:10 info › [logger] logger initialized
22:32:10 info › [electron] utils.ts
22:32:10 info › [preload] dirname /tmp/.mount_R3PLAYUw6792/resources/app.asar/main
22:32:10 info › [preload] userData path: /home/user/.config/R3PLAYX
22:32:10 info › [sentry] sentry initializing
22:32:10 info › [sentry] sentry initialized
22:32:10 info › [electron] db.ts
22:32:10 info › [db] Initializing database...
22:32:10 info › [db] Initializing database tables...
22:32:10 info › [db] Database tables initialized.
22:32:10 info › [db] Migrating database..
22:32:10 info › [db] Database migrated.
22:32:10 info › [db] Database initialized.
22:32:10 info › [electron] cache.ts
22:32:10 info › [electron] store.ts
22:32:10 info › [electron] menu.ts
22:32:10 info › [electron] ipcMain.ts
22:32:10 info › [electron] tray.ts
22:32:10 info › [electron] windowsTaskbar.ts
22:32:10 info › [electron] appServer/routes/r3play/appleMusic.ts
22:32:10 info › [electron] appServer/routes/r3play/audio.ts
22:32:10 info › [electron] appServer/appServer.ts
22:32:10 info › [electron] index.ts
22:32:10 info › [index] Main process start
```
之后就退出了，没有任何窗口。

**Comment by Sherlockouo** [comment]
好像确实，但是为啥呢。。。

**Comment by yuzh0816** [comment]
在显示这些内容之前有没有显示过其他内容？我记得显示这些信息前命令行会刷新，你看看如果有的话把之前的内容也发一下

**Comment by clean-master** [comment]
> 在显示这些内容之前有没有显示过其他内容？我记得显示这些信息前命令行会刷新，你看看如果有的话把之前的内容也发一下

没有。

我有看到#42 同样在linux上有问题，试了一下：
```bash
./R3PLAYX-2.6.0-linux.AppImage 
```
```
06:02:09 info › 

██╗   ██╗███████╗███████╗██████╗ ██╗      █████╗ ██╗   ██╗███╗   ███╗██╗   ██╗███████╗██╗ ██████╗
╚██╗ ██╔╝██╔════╝██╔════╝██╔══██╗██║     ██╔══██╗╚██╗ ██╔╝████╗ ████║██║   ██║██╔════╝██║██╔════╝
 ╚████╔╝ █████╗  ███████╗██████╔╝██║     ███████║ ╚████╔╝ ██╔████╔██║██║   ██║███████╗██║██║     
  ╚██╔╝  ██╔══╝  ╚════██║██╔═══╝ ██║     ██╔══██║  ╚██╔╝  ██║╚██╔╝██║██║   ██║╚════██║██║██║     
   ██║   ███████╗███████║██║     ███████╗██║  ██║   ██║   ██║ ╚═╝ ██║╚██████╔╝███████║██║╚██████╗
   ╚═╝   ╚══════╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝

06:02:09 info › [logger] logger initialized
06:02:09 info › [electron] utils.ts
06:02:09 info › [preload] dirname /tmp/.mount_R3PLAYAfMmWg/resources/app.asar/main
06:02:09 info › [preload] userData path: /home/user/.config/R3PLAYX
06:02:09 info › [sentry] sentry initializing
06:02:09 info › [sentry] sentry initialized
06:02:09 info › [electron] db.ts
06:02:09 info › [db] Initializing database...
06:02:10 info › [db] Initializing database tables...
06:02:10 info › [db] Database tables initialized.
06:02:10 info › [db] Migrating database..
06:02:10 info › [db] Database migrated.
06:02:10 info › [db] Database initialized.
06:02:10 info › [electron] cache.ts
06:02:10 info › [electron] ipcMain.ts
06:02:10 info › [electron] tray.ts
06:02:10 info › [electron] windowsTaskbar.ts
06:02:10 info › [electron] menu.ts
06:02:10 info › [electron] store.ts
06:02:10 info › [electron] appServer/routes/r3play/appleMusic.ts
06:02:10 info › [electron] appServer/routes/r3play/audio.ts
06:02:10 info › [electron] appServer/appServer.ts
06:02:10 info › [electron] index.ts
06:02:10 info › [index] Main process start
06:02:10 info › [index] App ready
06:02:10 info › [appServer] http server listening on port 42710
libva error: vaGetDriverNames() failed with unknown libva error
```
2.6.0可以正常使用。

**Comment by yuzh0816** [comment]
> > 在显示这些内容之前有没有显示过其他内容？我记得显示这些信息前命令行会刷新，你看看如果有的话把之前的内容也发一下
> 
> 
> 
> 没有。
> 
> 
> 
> 我有看到#42 同样在linux上有问题，试了一下：
> 
> ```bash
> 
> ./R3PLAYX-2.6.0-linux.AppImage 
> 
> ```
> 
> ```
> 
> 06:02:09 info › 
> 
> 
> 
> ██╗   ██╗███████╗███████╗██████╗ ██╗      █████╗ ██╗   ██╗███╗   ███╗██╗   ██╗███████╗██╗ ██████╗
> 
> ╚██╗ ██╔╝██╔════╝██╔════╝██╔══██╗██║     ██╔══██╗╚██╗ ██╔╝████╗ ████║██║   ██║██╔════╝██║██╔════╝
> 
>  ╚████╔╝ █████╗  ███████╗██████╔╝██║     ███████║ ╚████╔╝ ██╔████╔██║██║   ██║███████╗██║██║     
> 
>   ╚██╔╝  ██╔══╝  ╚════██║██╔═══╝ ██║     ██╔══██║  ╚██╔╝  ██║╚██╔╝██║██║   ██║╚════██║██║██║     
> 
>    ██║   ███████╗███████║██║     ███████╗██║  ██║   ██║   ██║ ╚═╝ ██║╚██████╔╝███████║██║╚██████╗
> 
>    ╚═╝   ╚══════╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝
> 
> 
> 
> 06:02:09 info › [logger] logger initialized
> 
> 06:02:09 info › [electron] utils.ts
> 
> 06:02:09 info › [preload] dirname /tmp/.mount_R3PLAYAfMmWg/resources/app.asar/main
> 
> 06:02:09 info › [preload] userData path: /home/user/.config/R3PLAYX
> 
> 06:02:09 info › [sentry] sentry initializing
> 
> 06:02:09 info › [sentry] sentry initialized
> 
> 06:02:09 info › [electron] db.ts
> 
> 06:02:09 info › [db] Initializing database...
> 
> 06:02:10 info › [db] Initializing database tables...
> 
> 06:02:10 info › [db] Database tables initialized.
> 
> 06:02:10 info › [db] Migrating database..
> 
> 06:02:10 info › [db] Database migrated.
> 
> 06:02:10 info › [db] Database initialized.
> 
> 06:02:10 info › [electron] cache.ts
> 
> 06:02:10 info › [electron] ipcMain.ts
> 
> 06:02:10 info › [electron] tray.ts
> 
> 06:02:10 info › [electron] windowsTaskbar.ts
> 
> 06:02:10 info › [electron] menu.ts
> 
> 06:02:10 info › [electron] store.ts
> 
> 06:02:10 info › [electron] appServer/routes/r3play/appleMusic.ts
> 
> 06:02:10 info › [electron] appServer/routes/r3play/audio.ts
> 
> 06:02:10 info › [electron] appServer/appServer.ts
> 
> 06:02:10 info › [electron] index.ts
> 
> 06:02:10 info › [index] Main process start
> 
> 06:02:10 info › [index] App ready
> 
> 06:02:10 info › [appServer] http server listening on port 42710
> 
> libva error: vaGetDriverNames() failed with unknown libva error
> 
> ```
> 
> 2.6.0可以正常使用。
> 
> 

尝试下他的解决办法呢，你看看能不能解决

```

在项目目录下将.env.example 复制为 .env ，重新编译electron打包

```

**Comment by Sherlockouo** [comment]
我在群里重新发一个linux版本的你们试试呢

**Comment by yuzh0816** [comment]
The bug is caused by the loss of .env file. Will be fixed in the next release.
