### ISSUE TITLE
关于换源问题

### ISSUE THREAD

**Issue by lijingbonb** [Sherlockouo/music#54]
我开通了网易云黑胶，还有qq音乐的绿钻但是还是提示需要开通会员后畅听
芦笋-aD4f_芦笋视频-20231119
链接：https://lusun.com/v/SrNEiKDrxPo

**Comment by Sherlockouo** [comment]
你可以在群里私发下cookie，我改了下代码测试下。

**Comment by Sherlockouo** [comment]
还是有问题 holy moly！！
