### ISSUE TITLE
[macOS]关于开启桌面歌词的情况下关闭主窗口会导致无法再次开启主窗口的bug

### ISSUE THREAD

**Issue by appe233** [Sherlockouo/music#56]
# 关于平台
我现在只有mac，不好测试别的

# 问题
正常安装软件。在设置里**开启桌面歌词**，**同时开启**最小化窗口里面的最小化选项。然后按一下播放器上的按钮显示桌面歌词。此时没有任何问题。然后关闭主窗口。接下来就不能再打开主窗口了。Dock里面右键显示所有窗口也只会显示歌词窗口。

这是我的设置：
<img width="1013" alt="Screenshot 2023-11-19 at 19 13 21" src="https://github.com/Sherlockouo/music/assets/89209249/4873f840-230c-43cf-ad8c-b971eddeb46c">
<img width="1013" alt="Screenshot 2023-11-19 at 19 13 37" src="https://github.com/Sherlockouo/music/assets/89209249/ea89eaf2-1e00-42c6-b4df-bbef7a8c3544">

**Comment by Sherlockouo** [comment]
好像是因为没有做mac的tray菜单，你先别两个都开
