### ISSUE TITLE
mac端图标大小不统一

### ISSUE THREAD

**Issue by kksxsyj** [Sherlockouo/music#57]
![image](https://github.com/Sherlockouo/music/assets/74647878/52c6ae05-df07-4c8d-a05b-4e9100255766)
如图，大小过大不和谐。

**Comment by Sherlockouo** [comment]
你会切图不？

**Comment by kksxsyj** [comment]
> 你会切图不？
不会啊，我自己在https://macosicons.com网站上找了个图标手动换了

**Comment by yuzh0816** [comment]
Planned to be fixed in the next week.

**Comment by Sherlockouo** [comment]
已修复，请前往[Release](https://github.com/Sherlockouo/music/releases/tag/2.7.1)下载
