### ISSUE TITLE
Mac 版本安装后无法打开，提示已损坏，或打开后没有窗口

### ISSUE THREAD

**Issue by equationzhao** [Sherlockouo/music#6]
OS: macOS Sonoma 14.0 23A5328b arm64
Host: MacBook Air (M2, 2022)

arm64 版本提示已损坏
<img width="260" alt="image" src="https://github.com/Sherlockouo/music/assets/75521101/ff9331b6-d216-4dd2-83d0-85fcf539d781">

Universal 版本打开没有窗口

系统是测试版 macOS，有可能是这个原因，正式版系统还没测试

**Comment by equationzhao** [comment]
虚拟机试了一下 
13.5.1 正式版系统也没有窗口页面

**Comment by Sherlockouo** [comment]
哦？有这事儿？ 
可以试试这个 M1芯片的Mac运行时提示已损坏怎么办？
安装YesPlayMusic后，在终端里执行 xattr -r -d com.apple.quarantine /Applications/YesPlayMusic.app 就可以了
