### ISSUE TITLE
最小化后图标右键功能

### ISSUE THREAD

**Issue by kksxsyj** [Sherlockouo/music#60]
能否增加一下最小化后图标右键菜单功能，比如下一曲之类的，当然如果能像官方那样增加任务栏功能那就更完美了！！！
![截屏2023-11-20 20 52 49](https://github.com/Sherlockouo/music/assets/74647878/c11d065e-b2f1-4524-88aa-037a7ef6ccca)
![截屏2023-11-20 21 11 18](https://github.com/Sherlockouo/music/assets/74647878/8a8765db-6ef7-4d4e-9851-2dca71c29082)

**Comment by yuzh0816** [comment]
收到建议！下周将会添加这个功能！

**Comment by Sherlockouo** [comment]
<img width="397" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/a94bf172-5584-4a51-a06b-dd3f6632cd28">
在加了

**Comment by Sherlockouo** [comment]
<img width="250" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/2f1f3311-d7c9-4606-9a18-88f869d918bf">

**Comment by Sherlockouo** [comment]
Done [Only for MacOS v2.7.1](https://github.com/Sherlockouo/music/releases/tag/2.7.1)
