### ISSUE TITLE
艺术家收藏功能无效

### ISSUE THREAD

**Issue by acdcbyl** [Sherlockouo/music#64]
当使用收藏艺术家的功能时，会显示已收藏，但是在艺人内无法找到；当返回到艺术家主页，发现收藏的红心消失。收藏歌曲/视频以及专辑功能正常。
![](http://cdn.aiser1314.xyz/202311221536883.png)

**Comment by Sherlockouo** [comment]
了解

**Comment by Sherlockouo** [comment]
你是哪个版本？哪个系统 我这边测试是正常的捏。。。

**Comment by Sherlockouo** [comment]
可能是收藏的时候报错了 emmm 可以提供更多日志 视频 截图 报错么？
