### ISSUE TITLE
Debian12 Wayland下严重的动画性能问题

### ISSUE THREAD

**Issue by AXFOX** [Sherlockouo/music#66]
如题，运行时动画非常卡顿，不过原仓库的版本没这个问题，感觉和Electron的硬件加速有关？
xfox@ThinkPadE14Gen3:~/下载$ ./R3PLAYX-2.7.1-linux.AppImage 
20:55:03 info › 

   _  __   __     _     ____                    __  ___                    _        
  | |/ /  / /_   (_)   / __/   __  __          /  |/  /  __  __   _____   (_)  _____
  |   /  / __/  / /   / /_    / / / /         / /|_/ /  / / / /  / ___/  / /  / ___/ 
 /   |  / /_   / /   / __/   / /_/ /         / /  / /  / /_/ /  (__  )  / /  / /__  
/_/|_|  \__/  /_/   /_/      \__, /         /_/  /_/   \__,_/  /____/  /_/   \___/  
                            /____/

20:55:03 info › [logger] logger initialized
20:55:03 info › [electron] utils.ts
20:55:03 info › [preload] dirname /tmp/.mount_R3PLAY095GPJ/resources/app.asar/main
20:55:03 info › [preload] userData path: /home/xfox/.config/R3PLAYX
20:55:03 info › [sentry] sentry initializing
20:55:03 info › [sentry] sentry initialized
20:55:03 info › [electron] db.ts
20:55:03 info › [db] Initializing database...
20:55:04 info › [db] Initializing database tables...
20:55:04 info › [db] Database tables initialized.
20:55:04 info › [db] Migrating database..
20:55:04 info › [db] Database migrated.
20:55:04 info › [db] Database initialized.
20:55:04 info › [electron] cache.ts
20:55:04 info › [electron] store.ts
20:55:04 info › [electron] menu.ts
20:55:04 info › [electron] ipcMain.ts
20:55:04 info › [electron] tray.ts
20:55:04 info › [electron] windowsTaskbar.ts
20:55:04 info › [electron] appServer/routes/r3play/appleMusic.ts
20:55:04 info › [electron] appServer/routes/r3play/audio.ts
20:55:04 info › [electron] appServer/appServer.ts
20:55:04 info › [electron] index.ts
20:55:04 info › [index] Main process start
20:55:04 info › [index] App ready
20:55:04 info › [appServer] http server listening on port 42710
20:55:04 info › checkForUpdates
20:55:04 info › Checking for update
20:55:05 debug › [server] Audio cache hit 5238992
20:55:10 info › Update for version 2.7.1 is not available (latest version: 2.7.1, downgrade is disallowed).
20:55:10 debug › checkForUpdatesAndNotify called, downloadPromise is null
启动日志没看出来有帮助的信息

**Comment by Sherlockouo** [comment]
最近正在优化这个性能问题

**Comment by Sherlockouo** [comment]
做了一些优化可以去 action里面下载测试版来试试

**Comment by Sherlockouo** [comment]
试下新版的呢？ https://github.com/Sherlockouo/music/actions/runs/7084599575
