### ISSUE TITLE
【BUG】任务栏图标icon显示不全

### ISSUE THREAD

**Issue by LeonYang98** [Sherlockouo/music#78]
win11
版本:2.7.2
![屏幕截图 2023-12-11 162802](https://github.com/Sherlockouo/music/assets/137973391/e5c2b948-9c8e-4777-9908-82f0faae5fe1)

**Comment by Sherlockouo** [comment]
woc

**Comment by LeonYang98** [comment]
> woc

你有复现出来吗？？

**Comment by yuzh0816** [comment]
> > woc
> 
> 
> 
> 你有复现出来吗？？

隔两天我去看看，我是win11 beta，你的版本号是什么？你看看2.7.0和2.7.1版本的有没有问题？

**Comment by LeonYang98** [comment]
> > > woc
> > 
> > 
> > 你有复现出来吗？？
> 
> 隔两天我去看看，我是win11 beta，你的版本号是什么？你看看2.7.0和2.7.1版本的有没有问题？

我是Windows 11 家庭中文版，2.7.0和2.7.1版本没有这个问题

**Comment by Sherlockouo** [comment]
> > woc
> 
> 你有复现出来吗？？

复现了 tmd 不知道是不是windows系统的问题

**Comment by Sherlockouo** [comment]
修了 图标出了点问题
