### ISSUE TITLE
能够启动软件但无法正常显示

### ISSUE THREAD

**Issue by KygoMarsh** [Sherlockouo/music#79]
[34570:1214/224946.361020:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[34570:1214/224946.363849:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[34570:1214/224946.365777:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

以上为报错信息

**Comment by KygoMarsh** [comment]
这是在linux下使用./R3PLAYX-2.7.2-linux.AppImage --no-sandbox的结果，是在root用户下执行的

**Comment by Sherlockouo** [comment]
新东西，没见过的版本

**Comment by Sherlockouo** [comment]
你直接执行 不加启动参数呢

**Comment by KygoMarsh** [comment]
抱歉，我的问题没有得到解决

**Comment by Sherlockouo** [comment]
还有其他的报错，信息可以提供吗？比如你的系统，cpu架构啥的。

**Comment by KygoMarsh** [comment]
现在程序跨越正常启动了，但是无法显示扫码界面
![1](https://github.com/Sherlockouo/music/assets/130618175/5fc088ba-c3cf-4fd9-bd2c-02c1b8f814d6)
![2 png](https://github.com/Sherlockouo/music/assets/130618175/47105847-1c59-4a52-912c-205003e56435)
`logger] logger initialized
12:35:52 info › [electron] utils.ts
12:35:52 info › [preload] dirname /tmp/.mount_R3PLAY3UbR8q/resources/app.asar/main
12:35:52 info › [preload] userData path: /home/kygomarsh/.config/R3PLAYX
12:35:52 info › [sentry] sentry initializing
12:35:52 info › [sentry] sentry initialized
12:35:52 info › [electron] db.ts
12:35:52 info › [db] Initializing database...
12:35:52 info › [db] Initializing database tables...
12:35:52 info › [db] Database tables initialized.
12:35:52 info › [db] Migrating database..
12:35:52 info › [db] Database migrated.
12:35:52 info › [db] Database initialized.
12:35:52 info › [electron] cache.ts
12:35:52 info › [electron] store.ts
12:35:52 info › [electron] menu.ts
12:35:52 info › [electron] ipcMain.ts
12:35:52 info › [electron] tray.ts
12:35:52 info › [electron] windowsTaskbar.ts
12:35:52 info › [electron] appServer/routes/r3play/appleMusic.ts
12:35:53 info › [electron] appServer/routes/r3play/audio.ts
12:35:53 info › [electron] appServer/appServer.ts
12:35:53 info › [electron] index.ts
12:35:53 info › [index] Main process start
12:35:53 info › [index] App ready
12:35:54 info › [appServer] http server listening on port 42710
12:35:54 info › checkForUpdates
12:35:54 info › Checking for update
12:38:09 info › {
  status: 502,
  body: {
    code: 502,
    msg: {
      message: 'connect ETIMEDOUT 240e:f7:4019:65::5:443',
      name: 'Error',
      stack: 'Error: connect ETIMEDOUT 240e:f7:4019:65::5:443\n' +
        '    at AxiosError.from (/tmp/.mount_R3PLAY3UbR8q/resources/app.asar/node_modules/axios/dist/node/axios.cjs:836:14)\n' +
        '    at RedirectableRequest.handleRequestError (/tmp/.mount_R3PLAY3UbR8q/resources/app.asar/node_modules/axios/dist/node/axios.cjs:3010:25)\n' +
        '    at RedirectableRequest.emit (node:events:513:28)\n' +
        '    at RedirectableRequest.emit (node:domain:489:12)\n' +
        '    at eventHandlers.<computed> (/tmp/.mount_R3PLAY3UbR8q/resources/app.asar/node_modules/follow-redirects/index.js:14:24)\n' +
        '    at ClientRequest.emit (node:events:525:35)\n' +
        '    at ClientRequest.emit (node:domain:489:12)\n' +
        '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +
        '    at TLSSocket.emit (node:events:513:28)\n' +
        '    at TLSSocket.emit (node:domain:489:12)',
      config: [Object],
      code: 'ETIMEDOUT',
      status: null
    }
  },
  cookie: []
}
12:38:11 info › Update for version 2.7.2 is not available (latest version: 2.7.2, downgrade is disallowed).
12:38:11 debug › checkForUpdatesAndNotify called, downloadPromise is null

`
上述结果是终端运行的情况，我不太清楚是否需要进行其他设置

**Comment by Sherlockouo** [comment]
ctrl +shift +i 看下控制台有报错嘛？或者你群里私信我，我给你远程给你看看

**Comment by KygoMarsh** [comment]
不知道什么原因，我重启电脑后再试一下就成功了！谢谢你

**Comment by que1jue** [comment]
我也有同样的问题现象，不过原因好像不同

![image](https://github.com/Sherlockouo/music/assets/81430318/fc62b0b3-1fb3-45aa-bd94-2f70f85b981f)
