### ISSUE TITLE
添加功能：调用服务器的音箱播放歌曲

### ISSUE THREAD

**Issue by huaimi123** [Sherlockouo/music#83]
假设我在linux设备上使用docker来安装，能不能通过 调用linux上的VLC播放器接口（或者内置一个VLC，MPD之类的）来实现 手机访问网页点歌，linux音箱放歌的效果。(也能切换成手机放歌，也能切换成linux音箱放歌)

**Comment by Sherlockouo** [comment]
你会写吗？或者有类似的实践可以借鉴吗？

**Comment by huaimi123** [comment]
(旧版)https://github.com/shaonianzhentan/cloud_music
(新版)https://github.com/shaonianzhentan/ha_cloud_music
我曾在这 旧版 的项目中见过，好像是内置了VLC播放器，手机访问homeassistant的web界面点歌，放歌，声音可以从主机音箱出来
新版 好像 移除了内置的VLC，需要自己安装。然后也是一样调用 VLC吧

**Comment by huaimi123** [comment]
> 你会写吗？或者有类似的实践可以充实吗？

（旧版）https://github.com/shaonianzhentan/cloud_music
（新版）https://github.com/shaonianzhentan/ha_cloud_music
我曾在这个旧版的项目中见过，希望内置了VLC播放器，手机访问homeassistant的网页界面点歌，放歌，声音可以从主机音箱出来
新版本希望删除了内置的VLC，需要自己安装。然后也一样调用VLC吧
