### ISSUE TITLE
请问是否可以添加一个网页访问的Token

### ISSUE THREAD

**Issue by LimLLL** [Sherlockouo/music#87]
因为是私有化部署的话，是否可以添加一个进入网页前需要输入predfined的token，不然只要别人知道服务器地址或者域名都能进行访问

**Comment by Sherlockouo** [comment]
细说

**Comment by LimLLL** [comment]
> 细说

就是类似于chatgpt nextweb项目类似，项目部署时需要一个自己设置的token密码，别人进来需要输入正确密码才能使用。

**Comment by yuzh0816** [comment]
这个应该可以通过自己配置搞定的，感觉没有必要加入到软件功能中，毕竟用户数据是存储在cookies中的，没必要加密访问吧。
